export const MAX_JSON_REQUEST_BYTES = 2 * 1024 * 1024;
export const MAX_MULTIPART_OVERHEAD_BYTES = 1024 * 1024;

export const MAX_THREAD_ID_CHARS = 128;
export const MAX_MODEL_ID_CHARS = 256;
export const MAX_PROMPT_CHARS = 20_000;
export const MAX_NEGATIVE_PROMPT_CHARS = 20_000;
export const MAX_CHAT_MESSAGE_CHARS = 100_000;
export const MAX_CHAT_MESSAGES = 200;
export const MAX_CHAT_REQUEST_TEXT_CHARS = 1_000_000;
export const MAX_CHAT_REQUEST_ATTACHMENTS = 30;
export const MAX_ATTACHMENTS_PER_MESSAGE = 6;

export const MAX_ATTACHMENT_ID_CHARS = 200;
export const MAX_ATTACHMENT_NAME_CHARS = 255;
export const MAX_ATTACHMENT_MIME_TYPE_CHARS = 255;
export const MAX_ATTACHMENT_PATH_CHARS = 1024;
export const MAX_ATTACHMENT_URL_CHARS = 8192;
export const MAX_ATTACHMENT_SIZE_BYTES = 100 * 1024 * 1024;

export const MAX_CLEANUP_PATHS = 100;
